# Generated by Django 5.0.2 on 2024-03-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KartaPaliwowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_karty", models.CharField(max_length=255)),
                ("nr_rejestracyjny", models.CharField(max_length=20)),
                ("data_ważności", models.DateField()),
                ("kod_pin", models.CharField(max_length=4)),
                (
                    "typ_karty",
                    models.CharField(
                        choices=[("S", "Samochód"), ("K", "Kierowca")], max_length=1
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "limit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C_3/60+120", "C_3/60+120"),
                            ("C_3/60+120+AutoGaz", "C_3/60+120+AutoGaz"),
                            ("C_1/75+120", "C_1/75+120"),
                            ("C_1/600+120", "C_1/600+120"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ogumienie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_rejestracyjny", models.CharField(max_length=20)),
                (
                    "rodzaj",
                    models.CharField(
                        choices=[
                            ("letnie", "Letnie"),
                            ("zimowe", "Zimowe"),
                            ("całoroczne", "Całoroczne"),
                        ],
                        max_length=15,
                    ),
                ),
                ("rozmiar", models.CharField(max_length=20)),
                (
                    "stan_lewy_przod",
                    models.CharField(
                        choices=[
                            ("dobry", "Dobry"),
                            ("do wymiany", "Do wymiany"),
                            ("uszkodzony", "Uszkodzony"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "stan_lewy_tyl",
                    models.CharField(
                        choices=[
                            ("dobry", "Dobry"),
                            ("do wymiany", "Do wymiany"),
                            ("uszkodzony", "Uszkodzony"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "stan_prawy_przod",
                    models.CharField(
                        choices=[
                            ("dobry", "Dobry"),
                            ("do wymiany", "Do wymiany"),
                            ("uszkodzony", "Uszkodzony"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "stan_prawy_tyl",
                    models.CharField(
                        choices=[
                            ("dobry", "Dobry"),
                            ("do wymiany", "Do wymiany"),
                            ("uszkodzony", "Uszkodzony"),
                        ],
                        max_length=15,
                    ),
                ),
                ("uwagi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pojazd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka_pojazdu", models.CharField(max_length=255)),
                ("model_pojazdu", models.CharField(max_length=255)),
                (
                    "rodzaj_pojazdu",
                    models.CharField(
                        choices=[
                            ("osobowy", "Osobowy"),
                            ("ciężarowy", "Ciężarowy"),
                            ("naczepa", "Naczepa"),
                            ("ciągnik siodłowy", "ciągnik sidołowy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rok_produkcji", models.IntegerField()),
                ("nr_rejestracyjny", models.CharField(max_length=20)),
                ("rok_pierwszej_rejestracji", models.IntegerField()),
                ("nr_vin", models.CharField(max_length=17)),
                ("moc", models.FloatField()),
                ("poj_silnika", models.FloatField()),
                (
                    "paliwo",
                    models.CharField(
                        choices=[("benzyna", "Pb95"), ("olej napędowy", "ON")],
                        max_length=15,
                    ),
                ),
                (
                    "wlasciciel",
                    models.CharField(
                        choices=[
                            ("srodek_wlasny", "Własność Spółki"),
                            ("leasing", "LEASING"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=255)),
                ("nazwisko", models.CharField(max_length=255)),
                ("stanowisko", models.CharField(max_length=255)),
                ("dzial", models.CharField(max_length=255)),
                ("nr_rej_samochodu", models.CharField(max_length=20)),
                (
                    "koszty_działu",
                    models.IntegerField(
                        choices=[
                            (2000, "2000- KOSZTY POŚREDNIE PRODUKCJI"),
                            (2100, "2100- KOSZTY UTRZYMANIA RUCHU"),
                            (2200, "2200-KOSZTY NADZORU PRODUKCYJNEGO"),
                            (2210, "2210-KOSZTY GŁÓWNEGO SPAWALNIKA"),
                            (2230, "2230-KOSZTY WŁASNYCH SZKOLEŃ I PRAKTYK"),
                            (3300, "3300-KOSZTY NARZĘDZIOWNI"),
                            (4000, "4000-KOSZTY DZIAŁU KONTROLI WEWNĘTRZNEJ"),
                            (5100, "5100-DYREKTOR DS.HANDLOWYCH"),
                            (5110, "5110-KOSZTY DZIAŁU OFERTOWEGO"),
                            (5120, "5120-KOSZTY DZIAŁU HANDLOWEGO"),
                            (5200, "5200-KOSZTY DZIAŁU ZAKUPOW"),
                            (5300, "5300-KOSZTY DZIALU MARKETINGU"),
                            (5400, "5400-KOSZTY GOSPOD.MATER., LOGISTYKI I SPEDYCJI"),
                            (
                                6100,
                                "6100-DYREKTOR DS. PRODUKCJI, DS. PRZYGOT.I REALIZ.PRODU",
                            ),
                            (6110, "6110-KOSZTY DZIAŁU PRODUKCJI"),
                            (6120, "6120-KOSZTY DZIAŁU PRZYGOTOWANIA"),
                            (6130, "6130-KOSZTY DZIAŁU REALIZACJI"),
                            (6200, "6200-KOSZTY DZIAŁU PLANOWANIA I CYFRYZACJI"),
                            (6300, "6300-KOSZTY DZIAŁU TECHNICZNEGO"),
                            (6410, "6410-KOSZTY DZIALU MONTAZOWEGO"),
                            (6500, "6500-KOSZTY LABORATORIUM"),
                            (6510, "6510-KOSZTY DZIAŁU KONTROLI JAKOŚCI"),
                            (
                                6520,
                                "6520-KOSZTY DZIALU ZAPEWN.JAKOŚCI, BHP I OCHRONY ś",
                            ),
                            (6600, "6600-KOSZTY DZIAŁU INWESTYCJI"),
                            (6700, "6700-KOSZTY Z-CY DYREKTORA DS. TECHNOLOGII"),
                            (7000, "7000-KOSZTY RADY NADZORCZEJ"),
                            (7100, "7100-KOSZTY ZARZĄDU"),
                            (7110, "7110-KOSZTY BIURA ZARZĄDU"),
                            (7120, "7120-KOSZTY DORADCÓW ZARZADU"),
                            (7300, "7300-KOSZTY OBSŁUGI PRAWNEJ"),
                            (7310, "7310-KOSZTY DZIAŁU UMÓW"),
                            (7400, "7400-KOSZTY DZIAŁU FINANSOWO - KSIĘGOWEGO"),
                            (7510, "7510-KOSZTY DZIAŁU KONTROLINGU"),
                            (7600, "7600-KOSZTY WYDZIAłU ADMINISTRACYJNEGO"),
                            (7700, "7700-KOSZTY DZIAŁU INFORMATYKI"),
                            (7800, "7800-KOSZTY DZIAŁU PŁAC I ZZL"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TowarzystwoUbezpieczeniowe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("ulica", models.CharField(max_length=255)),
                ("miasto", models.CharField(max_length=255)),
                ("kod_pocztowy", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Warsztat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("adres_ulica", models.CharField(max_length=255)),
                ("adres_miasto", models.CharField(max_length=255)),
                ("adres_kod_pocztowy", models.CharField(max_length=10)),
                ("nip", models.CharField(max_length=10)),
                ("regon", models.CharField(max_length=14)),
                ("telefon", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("osoba_kontaktowa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Naprawa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_naprawy", models.CharField(max_length=255)),
                ("data_naprawy", models.DateField()),
                ("notatki", models.TextField()),
                (
                    "pojazd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.pojazd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Koszt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("opis", models.TextField()),
                (
                    "czesci",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "robocizna",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "suma",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "pojazd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.pojazd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BadanieTechniczne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_przegladu", models.CharField(max_length=255)),
                ("data_przegladu", models.DateField()),
                ("notatki", models.TextField()),
                (
                    "pojazd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.pojazd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Polisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_polisy", models.CharField(max_length=255)),
                (
                    "zakres",
                    models.CharField(
                        choices=[
                            ("złoty", "Złoty"),
                            ("platynowy", "Platynowy"),
                            ("złoty+", "Złoty+"),
                        ],
                        max_length=15,
                    ),
                ),
                ("data_rozpoczecia", models.DateField()),
                ("data_zakonczenia", models.DateField()),
                (
                    "nr_rej_pojazdu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.pojazd"
                    ),
                ),
                (
                    "towarzystwo_ubezpieczeniowe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleet.towarzystwoubezpieczeniowe",
                    ),
                ),
            ],
        ),
    ]
